(define results '())
;;; Test 1
; p = -8 + 2x + 3yx^2 + x + 0z + x^0x
(define p '((-8 (())) (2 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 1))) (0 ((z 1))) (1 ((x 0) (x 1)))))

;; Test Description:
;; This is possibly the worst-case (but still valid) polynomial in need of simplifying.
;; "Valid" means it can be generated by p+, p- or p* before being cleaned with (clean)
;; Like terms are separated by unlike terms and are not collected into one term
;; Like variables are not collected into one variable.
;; It contains a term with coefficient 0.
;; It contains a term with a variable raised to the power 0.

;; Test 1.1
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "1.1: ")
(define result (p= (simp-terms (simp-vars p)) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 1.2
(define expected '((-16 (())) (8 ((x 1))) (6 ((y 1) (x 2)))))
(display "1.2: ")
(define result (p= (p+ p p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 1.3
(define expected '((64 (())) (-64 ((x 1))) (-48 ((y 1) (x 2))) (16 ((x 2))) (12 ((x 3) (y 1))) (12 ((y 1) (x 3))) (9 ((y 2) (x 4)))))
(display "1.3: ")
(define result (p= (p* p p) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 2
; p = 0
; q =  -8 + 2x + 3yx^2 + x + 0z + x^0x
(define p '((0 (()))))
(define q '((-8 (())) (2 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 1))) (0 ((z 1))) (1 ((x 0) (x 1)))))

;; Test Description:
;; Check that we can perform operations with 0 on both sides of each operator
;; Tests 2.2 - 2.4: 0 on left side
;; Tests 2.5 - 2.7: 0 on right side

;; Test 2.1
(define expected '())
(display "2.1: ")
(define result (p= (simp-terms (simp-vars p)) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.2
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "2.2: ")
(define result (p= (p+ p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.3
(define expected '((8 (())) (-4 ((x 1))) (-3 ((y 1) (x 2)))))
(display "2.3: ")
(define result (p= (p- p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.4
(define expected '())
(display "2.4: ")
(define result (p= (p* p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.5
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "2.5: ")
(define result (p= (p+ q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.6
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "2.6: ")
(define result (p= (p- q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 2.7
(define expected '())
(display "2.7: ")
(define result (p= (p* q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 3
; p = -8 + 2x + 3yx^2 + x + 0z + x^0x
; q = 2x - 8 + x + 3yx^2 + x^0x + 0z
(define p '((-8 (())) (2 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 1))) (0 ((z 1))) (1 ((x 0) (x 1)))))
(define q '((2 ((x 1))) (-8 (())) (1 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 0) (x 1))) (0 ((z 1)))))

;; Test Description:
;; To test p=, since p and q are equal?, but their terms are not in the same order.

;; Test 3.1
(define expected #t)
(display "3.1: ")
(define result (equal? (p= p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 4
; p = 3yx^2 
; q = 3x^2y
(define p '((3 ((y 1) (x 2)))))
(define q '((3 ((x 2) (y 1)))))

;; Test Description:
;; To test all operators since p and q are equal?, but their variables are not in the same order

;; Test 4.1
(define expected #t)
(display "4.1: ")
(define result (equal? (p= p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 4.2
(define expected '((6 ((y 1) (x 2)))))
(display "4.2: ")
(define result (p= (p+ p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 4.3
(define expected '())
(display "4.3: ")
(define result (equal? (p- p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 4.4
(define expected '((9 ((y 2) (x 4)))))
(display "4.4: ")
(define result (p= (p* p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;;: Test 5
; p = 3yx^2
; q = 3yx^3
(define p '((3 ((y 1) (x 2)))))
(define q '((3 ((y 1) (x 3)))))

;; Test Description:
;; To test p=, since p and q are same length with same number of variables, but one variable has unequal powers

;; Test 5.1
(define expected #f)
(display "5.1: ")
(define result (equal? (p= p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 6
; p = 1
; q =  -8 + 2x + 3yx^2 + x + 0z + x^0x
(define p '((1 (()))))
(define q '((-8 (())) (2 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 1))) (0 ((z 1))) (1 ((x 0) (x 1)))))

;; Test Description:
;; Check that we can perform operations with 1 on both sides of each operator
;; Tests 6.1 - 6.3: 1 on left side
;; Tests 6.4 - 6.6: 1 on right side

;; Test 6.1
(define expected '((-7 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "6.1: ")
(define result (p= (p+ p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 6.2
(define expected '((9 (())) (-4 ((x 1))) (-3 ((y 1) (x 2)))))
(display "6.2: ")
(define result (p= (p- p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 6.3
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "6.3: ")
(define result (p= (p* p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 6.4
(define expected '((-7 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "6.4: ")
(define result (p= (p+ q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 6.5
(define expected '((-9 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "6.5: ")
(define result (p= (p- q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 6.6
(define expected '((-8 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "6.6: ")
(define result (p= (p* q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 7
; p = -1
; q =  -8 + 2x + 3yx^2 + x + 0z + x^0x
(define p '((-1 (()))))
(define q '((-8 (())) (2 ((x 1))) (3 ((y 1) (x 2))) (1 ((x 1))) (0 ((z 1))) (1 ((x 0) (x 1)))))

;; Test Description:
;; Check that we can perform operations with -1 on both sides of each operator
;; Tests 7.1 - 7.3: -1 on left side
;; Tests 7.4 - 7.6: -1 on right side

;; Test 7.1
(define expected '((-9 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "7.1: ")
(define result (p= (p+ p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 7.2
(define expected '((7 (())) (-4 ((x 1))) (-3 ((y 1) (x 2)))))
(display "7.2: ")
(define result (p= (p- p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 7.3
(define expected '((8 (())) (-4 ((x 1))) (-3 ((y 1) (x 2)))))
(display "7.3: ")
(define result (p= (p* p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 7.4
(define expected '((-9 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "7.4: ")
(define result (p= (p+ q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 7.5
(define expected '((-7 (())) (4 ((x 1))) (3 ((y 1) (x 2)))))
(display "7.5: ")
(define result (p= (p- q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 7.6
(define expected '((8 (())) (-4 ((x 1))) (-3 ((y 1) (x 2)))))
(display "7.6: ")
(define result (p= (p* q p) expected))
(define results (cons result results))
(display result)
(display "\n")

;;; Test 8
; p = 3yx^2 + 2z^2x^3y
; q = 2x^3yz^2 + 3x^2y
(define p '((3 ((y 1) (x 2))) (2 ((z 2) (x 3) (y 1)))))
(define q '((2 ((x 3) (y 1) (z 2))) (3 ((x 2) (y 1)))))

;; Test Description:
;; A more thorough version of Test 4.
;; To test all operators, since p and q are equal?, but their variables and terms are not in the same order.

;; Test 8.1
(define expected #t)
(display "8.1: ")
(define result (equal? (p= p q) expected))
(define results (cons result results))
(display result)
(display "\n")
 
;; Test 8.2
(define expected '((6 ((y 1) (x 2))) (4 ((z 2) (x 3) (y 1)))))
(display "8.2: ")
(define result (p= (p+ p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 8.3
(define expected '())
(display "8.3: ")
(define result (equal? (p- p q) expected))
(define results (cons result results))
(display result)
(display "\n")

;; Test 8.4
(define expected '((12 ((y 2) (x 5) (z 2))) (9 ((y 2) (x 4))) (4 ((z 4) (x 6) (y 2)))))
(display "8.4: ")
(define result (p= (p* p q) expected))
(define results (cons result results))
(display result)
(display "\n")

(display "-----------\n")
(define passed-tests (foldr + 0 (map (lambda (x) (if (equal? x #t) 1 0)) results)))
(display (length results))
(display " run / ")
(display passed-tests)
(display " passed.\n")
